import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header className="border-b border-white/10">
            <nav className="max-w-6xl mx-auto p-4 flex gap-4 text-sm">
              <a href="/" className="hover:underline">Главная</a>
              <a href="/play" className="hover:underline">Играть</a>
              <a href="/gallery" className="hover:underline">Галерея</a>
              <a href="/users" className="hover:underline">Участники</a>
              <a href="/leaderboard" className="hover:underline">Лидерборд</a>
              <a href="/admin" className="ml-auto hover:underline">Админ</a>
            </nav>
          </header>
          <main className="min-h-screen">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
